import AuthProvider from "@/context/AuthProvider"
import type { Metadata } from "next"
import { Signika_Negative } from "next/font/google"
import "./globals.css"
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'
import Navbar from "@/components/shared/Navbar";

const inter = Signika_Negative({ subsets: ["latin"],weight:['400'] })

export const metadata: Metadata = {
  title: "Queue Overflow",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`bg-black text-white ${inter.className}`}>
        <AuthProvider>
          <Navbar />
          {children}
          <ToastContainer />
        </AuthProvider>
      </body>
    </html>
  )
}



